In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("spam_ham_5k.csv")
df.head()

Category                                            Message
0     spam  WINNER!! As a valued network customer you have...
1     spam  Lowest rates guaranteed! Refinance your loan now.
2      ham       Meeting is confirmed for 3 PM at the office.
3      ham  Thanks for your help earlier, I really appreci...
4     spam  Congratulations! You've won a free ticket to B...

In [17]:
df.Category.value_counts()

Category
spam    2500
ham     2500
Name: count, dtype: int64

In [18]:
df['spam']= df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [19]:
df.head()

Category                                            Message  spam
0     spam  WINNER!! As a valued network customer you have...     1
1     spam  Lowest rates guaranteed! Refinance your loan now.     1
2      ham       Meeting is confirmed for 3 PM at the office.     0
3      ham  Thanks for your help earlier, I really appreci...     0
4     spam  Congratulations! You've won a free ticket to B...     1

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size =0.2)

In [22]:
df.shape

(5000, 3)

In [23]:
X_train.shape

(4000,)

In [25]:
X_test.shape

(1000,)

In [26]:
type(X_train)

pandas.core.series.Series

In [27]:
X_train[:4]

1856    Free entry in 2 a wkly comp to win FA Cup fina...
3845                Let's catch up sometime this weekend.
4345           Good luck with your presentation tomorrow!
328            Happy Birthday! Hope you have a great day.
Name: Message, dtype: object

In [28]:
type(y_train)

pandas.core.series.Series

In [33]:
y_train[:4]

1856    1
3845    0
4345    0
328     0
Name: spam, dtype: int64

In [34]:

# CountVectorizer class
from sklearn.feature_extraction.text import CountVectorizer

v= CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 36544 stored elements and shape (4000, 132)>

In [36]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [37]:
X_train_cv.shape

(4000, 132)

In [41]:
# get words out of vocab

v.get_feature_names_out()

array(['000', '09061701461', '10', '12345', '2000', '2005', '21st',
       '54321', '87121', 'and', 'apply', 'appreciate', 'approved', 'are',
       'arriving', 'as', 'at', 'bahamas', 'been', 'birthday', 'bring',
       'by', 'call', 'cash', 'catch', 'claim', 'click', 'comp',
       'confirmed', 'congratulations', 'credit', 'cup', 'customer', 'day',
       'dinner', 'don', 'earlier', 'earn', 'entry', 'experience', 'fa',
       'final', 'for', 'forget', 'free', 'from', 'good', 'great',
       'guaranteed', 'happy', 'has', 'have', 'help', 'here', 'hey',
       'home', 'hope', 'in', 'investment', 'is', 'it', 'just', 'later',
       'let', 'line', 'll', 'loan', 'lowest', 'luck', 'may', 'meeting',
       'message', 'mobile', 'needed', 'network', 'no', 'not', 'now',
       'number', 'offering', 'office', 'opportunity', 'pm', 'pre',
       'presentation', 'prize', 'raining', 'rates', 're', 'really',
       'receive', 'refinance', 'report', 'reward', 'ringtone', 'selected',
       'send', 'som

In [42]:
v.get_feature_names_out().shape

(132,)

In [43]:
dir(v)   
# tell all methods available for that variable

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',


In [44]:
v.vocabulary_

{'free': 44,
 'entry': 38,
 'in': 57,
 'wkly': 127,
 'comp': 27,
 'to': 108,
 'win': 124,
 'fa': 40,
 'cup': 31,
 'final': 41,
 'tkts': 107,
 '21st': 6,
 'may': 69,
 '2005': 5,
 'text': 101,
 '87121': 8,
 'let': 63,
 'catch': 24,
 'up': 115,
 'sometime': 97,
 'this': 104,
 'weekend': 121,
 'good': 46,
 'luck': 68,
 'with': 126,
 'your': 131,
 'presentation': 84,
 'tomorrow': 109,
 'happy': 49,
 'birthday': 19,
 'hope': 56,
 'you': 130,
 'have': 51,
 'great': 47,
 'day': 33,
 'urgent': 116,
 'mobile': 72,
 'number': 78,
 'has': 50,
 'won': 128,
 '2000': 4,
 'cash': 23,
 'call': 22,
 '09061701461': 1,
 'now': 77,
 'is': 59,
 'not': 76,
 'spam': 98,
 'we': 120,
 're': 88,
 'offering': 79,
 'unique': 113,
 'investment': 58,
 'opportunity': 81,
 'don': 35,
 'forget': 43,
 'bring': 20,
 'umbrella': 112,
 'it': 60,
 'raining': 86,
 'thanks': 102,
 'for': 42,
 'help': 52,
 'earlier': 36,
 'really': 89,
 'appreciate': 11,
 'winner': 125,
 'as': 15,
 'valued': 117,
 'network': 74,
 'customer': 3

In [45]:
v.get_feature_names_out()[111]

'tonight'

In [46]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [47]:
np.where(X_train_np[0]!=0)
# tell where 1 are in array np

(array([  5,   6,   8,  27,  31,  38,  40,  41,  44,  57,  69, 101, 107,
        108, 124, 127]),)

In [51]:
X_train_np[0][127]

np.int64(1)

Build Model


In [52]:
from sklearn.naive_bayes import MultinomialNB

model =MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [54]:
X_test_cv = v.transform(X_test)

In [56]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       512
           1       1.00      1.00      1.00       488

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [59]:
emails = [
    "Hey Mohan, can we get together to watch football game tomorrow",
    "Upto 20% discount on parking, exclusive offer just for you. Don't miss the reward!"
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 0])

In [61]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [62]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [63]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       512
           1       1.00      1.00      1.00       488

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

